"""updated borrowed_books model

Revision ID: 012a1a3d9a0d
Revises: 113310f04dcd
Create Date: 2025-05-15 10:25:19.273760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '012a1a3d9a0d'
down_revision: Union[str, None] = '113310f04dcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
